version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Change to your required image
    steps:
      - checkout
      - run: python main.py

workflows:
  build_now:
    jobs:
      - build

